- engine/core/video/opengl/glimage.cpp
- engine/core/video/sdl/sdlimage.cpp
The previous fix only changed Image, but not GLImage and SDLImage
> Fixed the problem that image offsets were lost by image free() (again)

- engine/python/fife/extensions/fife_settings.py
found some old files that still contain some settings as int
that are now required to be boolean by the swig-bindings.
extended the settings-script to convert those values to bool
and print a deprecation warning to the log whenever it discovers
an unsupported type.
> forcing bool values for some setting

- CMakeLists.txt
to avoid the following error on windows:
```
CMake Error at CMakeLists.txt:550 (STRING):
string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
command.
```
> wrap the slash fix for PYTHON_SITE_PACKAGES in a not win32 condition

- setup.py
For example:
python setup.py set_metadata --version=0.4.1 bdist_wininst
Issue #908
> Add an option to setup.py to set package version from command line

- engine/core/controller/engine.cpp
This delete was commented out back in 2011 and caused a small memory leak when the engine was destroyed. I don't know if the destructor for EventManager should be edited, but my memory leak detection tool doesn't detect leaks from it.
> Fixed memory leak from 594852b caused by eventmanager

- engine/python/fife/extensions/fife_settings.py
This should prevent errors like the one in Issue #959
> Load default settings if settings file has no FIFE module

- CMakeLists.txt
In older versions (<3.0) of CMake, the UseSWIG.cmake module does some
matching against the SOURCE_DIR and then against the BINARY_DIR. If the
BIN_DIR has the SRC_DIR as a parent, the paths of certain files in the
generated Makefile might end up wrong and the files cannot be compiled.
With this patch, cmake does not allow the BINARY_DIR to have the
SOURCE_DIR as a parent for CMake versions < 3. Instead, it shows a hint
and exits.
> Don't allow "in-source-tree" build directory for older cmake

- engine/python/fife/extensions/pychan/widgets/icon.py
When creating an `Icon` with an invalid file path, the `Icon` object
first calls its parent's `__init__()` and then trys to load the image
source.  Loading the image might end up in e.g. `fife.NotFound`, but the
parent's `__init__()` already added the new `Icon` instance to the
manager. So while the code creating the `Icon` will never see an
instance of it and can never call `hide()` to remove it, the manager
still thinks that there's an instance available.
This commit changes to code to remove the `Icon` from the manager for
any occuring exception and then re-raise the exception.
> pychan: Remove Icon from manager on source load failure

- engine/core/model/metamodel/grids/cellgrid.h
- engine/core/model/metamodel/grids/cellgrids.i
- engine/core/model/metamodel/grids/hexgrid.cpp
- engine/core/model/metamodel/grids/hexgrid.h
- engine/core/model/metamodel/grids/squaregrid.cpp
- engine/core/model/metamodel/grids/squaregrid.h
- engine/core/model/structures/location.cpp
Location::getLayerCoordinates() converts from ExactLayerCoordinates to LayerCoordinates by naive conversion from float to int. This works fine on square grids, but can return the wrong coordinates when close to cell edge on hex grids.
The fix is to use the CellGrid methods instead. It's a two-step conversion (ExactLayer to Map to Layer). It can probably be optimized by removing the intermediate step, but I think it would require an additional CellGrid method.
> Fix Location::getLayerCoordinates() on hex grids

- engine/core/view/renderers/lightrenderer.cpp
Previously it used the camera zoom for scaling but ignored it for positioning, so lights got out of position when zooming.
> Use camera zoom when positioning lights in LightRenderer

- CMakeLists.txt
Because we're shipping shared objects there.
Also, use sys.stdout.write() to not bother CMake for trailing newline.
Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>
> build: install Python bindings into arch-specific directory

- engine/core/controller/engine.cpp
- engine/core/model/metamodel/grids/cellgrids.i
- engine/core/model/metamodel/grids/hexgrid.cpp
- engine/core/model/metamodel/grids/hexgrid.h
Using terminology from http://www.redblobgames.com/grids/hexagons/, the new system uses axial coordinates, while the old one uses offset coordinates. It can be used by specifying grid_type="hexagonal_axial" in the map file (the old one remains simply "hexagonal").
I've decided to reuse the existing class instead of making a new one, as there aren't that many changes between the two systems.
> Add an axial coordinate system for hex grid (#732)

- CMakeLists.txt
- engine/core/version.h.in
- engine/core/version.i
- remove all string expansion helpers
- version information and git metadata content is inserted by cmake
- added getVersionShort() = version without git hash
- added int getVersionId() = returns version 3.2.1 as 30201 (easier version comparison)
> Change version.h

- engine/core/video/opengl/renderbackendopengl.cpp
SDL_GL_SetSwapInterval() works for the current OpenGL context, so it needs to be called after creating it.
> Fix VSync setting

- CMakeLists.txt
This avoids the compiler error "C1128: number of sections exceeded object file format limit: compile with /bigobj"
> Add /bigobj compiler option for MSVC

- CMakeLists.txt
The compilation flag `-O` combines the following flags: `-modern -fastdispatch -nosafecstrings -fvirtual -noproxydel -fastproxy -fastinit -fastunpack -fastquery -modernargs -nobuildnone`. I found this in https://github.com/swig/swig/blob/73a5d6c187bb9dad7f17cc920774ec41d59968f0/Source/Modules/python.cxx#L165
I'm removing `-modern -modernargs`, because `-O` includes them.
Note for https://github.com/fifengine/fifengine/issues/712 : One might try reducing the build time by disabling compiler optimizations.
> tweak CMAKE_SWIG_FLAGS by adding -O

- engine/core/controller/engine.cpp
- engine/core/controller/engine.i
- engine/core/controller/enginesettings.cpp
- engine/core/controller/enginesettings.h
- engine/core/loaders/native/map/animationloader.h
- engine/core/loaders/native/map/ianimationloader.i
- engine/core/modules.h
- engine/core/video/cursor.cpp
- engine/core/video/cursor.h
- engine/core/video/opengl/glimage.cpp
- engine/core/video/video.i
- engine/python/fife/extensions/basicapplication.py
- engine/python/fife/extensions/fife_settings.py
Issue #1012 
This PR adds the native image cursor feature.
If enabled, cursors set to an image or an animation will be set using SDL and drawn by the native platform; otherwise they will be drawn by FIFE.
This setting has no effect on NativeCursor types which are always native and on the drag cursor which is always drawn by FIFE.
Animations are implemented by setting a new SDL cursor whenever the animation frame changes.
If creating the cursor fails we log the error and fall back to software cursor.
Animated cursors work fine when loaded with AnimationLoader, but when I tried to use object animations like this:
```
action = self.application.model.getObject(object_name, "steamfolktales").getAction("idle")
visual = action.get2dGfxVisual()
anim = …
```
> Native image cursor

- engine/core/loaders/native/map/maploader.cpp
- engine/core/model/structures/map.cpp
- engine/core/model/structures/map.h
- engine/core/model/structures/map.i
- engine/core/savers/native/map/mapsaver.cpp
- engine/core/view/camera.cpp
- engine/core/view/camera.h
- engine/core/view/camera.i
- engine/python/fife/extensions/serializers/xmlmap.py
- engine/python/fife/extensions/serializers/xmlmapsaver.py
- tests/swig_tests/action_tests.py
- tests/swig_tests/animation_tests.py
- tests/swig_tests/view_tests.py
The PR fix https://github.com/fifengine/fifengine/issues/305
For Clients it is enough to change the reference cell size in case the camera was bound to a layer with a cell grid scale that differs from 1.0. Additionally getLocationRef() from camera is gone.
> Simplify camera

- CMakeLists.txt
Python extension modules **should not** link directly to a Python library binary on `macOS`.
They should be linked with "-undefined dynamic_lookup" instead of "-lpython" or "-framework Python" for MacOS.
Adapting same modification to `CMakeLists.txt` of "0.4.1.tar.gz" , "CMakeFiles/_fifechan.dir/link.txt" changed to the following.
>/usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.13 -bundle -Wl,-headerpad_max_install_names  -o _fifechan.so CMakeFiles/_fifechan.dir/fifechanPYTHON_wrap.cxx.o  -L/usr/local/lib/libfifechan.dylib  -L/usr/local/lib/libfifechan_sdl.dylib  -L/usr/local/lib/libfifechan_opengl.dylib …
> CMakeLists.txt: Use `-undefined dynamic_lookup`

- engine/core/gui/cegui/base/ceguiinputprocessor.h
This is fix https://github.com/fifengine/fifengine/issues/1045.
> ceguiinputprocessor.h: include SDL.h

- CMakeLists.txt
Hi there,
I tried to compile fifengine on macOS Catalina and ran into compilation errors.
I edited CMakeLists.txt and removed
- nosafecstrings
- nobuildnone.
With those changes fifengine builds successfully.
> Remove unsupported command line options to fix compilation on macOS 10.15 (Catalina)

- engine/python/fife/extensions/serializers/simplexml.py
>Methods getchildren() and getiterator() of classes ElementTree and Element in the ElementTree module have been removed. They were deprecated in Python 3.2. Use iter(x) or list(x) instead of x.getchildren() and x.iter() or list(x.iter()) instead of x.getiterator(). (Contributed by Serhiy Storchaka in bpo-36543.)
https://docs.python.org/3.9/whatsnew/3.9.html#removed
> remove deprecated getchildren()

- engine/core/vfs/zip/zipnode.cpp
boost-1.77.0 no longer includes `<algorithm>`
Closes: #1080
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>
> Fix build against boost-1.77.0
